name: main
on:
  push:
    branches:
      - master
    tags:
      - v*

env:
  IMAGE: ${{secrets.DOCKER_REGISTRY}}/${{secrets.DOCKER_REGISTRY_NAMESPACE}}/gqmt

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Docker Login
        run: |
          echo $GITHUB_REPOSITORY
          echo $GITHUB_ACTOR
          docker login --username ${{ secrets.GITHUB_REPOSITORY_OWNER }} --password ${{ secrets.GITHUB_TOKEN }} ${{secrets.DOCKER_REGISTRY}}
                  
      - name: Docker Build
        run: docker build --tag ${IMAGE}:${GITHUB_REF##*/} --file ./docker/Dockerfile .
                    
      - name: Docker Push
        run: docker push ${IMAGE}:${GITHUB_REF##*/}
